import type { Config } from 'tailwindcss';

// The brand theme fragment is generated by build/build_tokens.py from the same
// source the artwork is drawn from. Editing colours here would let the site and
// the visual kit drift apart - change build/brand.py and regenerate instead.
// eslint-disable-next-line @typescript-eslint/no-var-requires
const brand = require('./tailwind.theme.cjs') as {
  theme: { extend: Record<string, unknown> };
};

const config: Config = {
  content: ['./app/**/*.{ts,tsx}', './components/**/*.{ts,tsx}'],
  theme: {
    extend: {
      ...brand.theme.extend,
      fontFamily: {
        display: ['var(--font-display)', 'ui-serif', 'Georgia', 'serif'],
        body: ['var(--font-body)', 'ui-sans-serif', 'system-ui', 'sans-serif'],
      },
      colors: {
        ...(brand.theme.extend.colors as Record<string, unknown>),
        // The semantic layer. These flip with the theme; the `at-*` scale does not.
        page: 'var(--at-bg)',
        surface: 'var(--at-surface)',
        content: 'var(--at-text)',
        muted: 'var(--at-text-muted)',
        hairline: 'var(--at-border)',
        link: 'var(--at-link)',
        accent: 'var(--at-accent)',
      },
      maxWidth: {
        prose: '68ch',
        container: '76rem',
        narrow: '48rem',
      },
      transitionDuration: { DEFAULT: '180ms' },
      transitionTimingFunction: { DEFAULT: 'cubic-bezier(0.22, 0.61, 0.36, 1)' },
    },
  },
  plugins: [],
};

export default config;
